#!/bin/bash

export WEBAPPS=/usr/share/tomcat/webapps
export ELDAGIT=/home/chris/EldaThings/elda-in-github
export SPECS=$ELDAGIT/elda-standalone/src/main/webapp/specs

service tomcat stop
rm -rf $WEBAPPS/*

cp $ELDAGIT/elda-assets/target/elda-assets.war $WEBAPPS
cp $ELDAGIT/elda-common/target/elda-common.war $WEBAPPS

cp /home/chris/EldaThings/elda-in-github/run-common/chris-config.ttl /etc/elda/conf.d/elda-common

rm -rf /var/log/tomcat/*
service tomcat start
