#!/bin/bash

export HTML="assembled"

#
# wrap the header & footer fragments around the .body files and write
# the result to the .html files.
#
for x in *body; do cat HEADER.fragment $x FOOTER.fragment > $HTML/$(basename $x .body).html; done
