#!/bin/bash

#
# wrap the header & footer fragments around the .body files and write
# the result to the .html files in the directory above this one.
#
for x in *body; do cat HEADER.fragment $x FOOTER.fragment > ../$(basename $x .body).html; done
