package com.epimorphics.lda.support.tests;

import static org.junit.Assert.*;

import java.util.Set;

import org.junit.Test;

import com.epimorphics.jsonrdf.utils.ModelIOUtils;
import com.epimorphics.lda.support.CycleFinder;
import com.epimorphics.util.CollectionUtils;
import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.Resource;

public class TestCycleFinder {
	
	@Test public void returnsNoCycleFromPlainStatement() {
		Model m = ModelIOUtils.modelFromTurtle( ":x rdf:type :T." );
		Resource x = m.createResource( m.expandPrefix( ":x" ) );
		Set<Resource> loops = CycleFinder.findCycles( x );
		assertEquals( CollectionUtils.set(), loops );
	}	
	
	@Test public void returnsNoCycleFromChainOfStatements() {
		Model m = ModelIOUtils.modelFromTurtle( ":x :P :y. :y :Q :z." );
		Resource x = m.createResource( m.expandPrefix( ":x" ) );
		Set<Resource> loops = CycleFinder.findCycles( x );
		assertEquals( CollectionUtils.set(), loops );
	}
	
	@Test public void returnsNoCycleFromParallelStatements() {
		Model m = ModelIOUtils.modelFromTurtle( ":x :P :y. :x :Q :z." );
		Resource x = m.createResource( m.expandPrefix( ":x" ) );
		Set<Resource> loops = CycleFinder.findCycles( x );
		assertEquals( CollectionUtils.set(), loops );
	}
	
	@Test  public void returnsSingleStatementCycle() {
		Model m = ModelIOUtils.modelFromTurtle( ":x :P :x." );
		Resource x = m.createResource( m.expandPrefix( ":x" ) );
		Set<Resource> loops = CycleFinder.findCycles( x );
		assertEquals( CollectionUtils.set(x), loops );
	}
	
	@Test  public void returnsMultiStatementCycle() {
		Model m = ModelIOUtils.modelFromTurtle( ":x :P :y. :y :Q :x." );
		Resource x = m.createResource( m.expandPrefix( ":x" ) );
		Resource y = m.createResource( m.expandPrefix( ":y" ) );
		Set<Resource> loops = CycleFinder.findCycles( x );
		assertEquals( CollectionUtils.set(x, y), loops );
	}
	
	@Test  public void returnsDeferedMultiStatementCycle() {
		Model m = ModelIOUtils.modelFromTurtle( ":x :P :y. :y :Q :z. :z :R :y." );
		Resource x = m.createResource( m.expandPrefix( ":x" ) );
		Resource y = m.createResource( m.expandPrefix( ":y" ) );
		Resource z = m.createResource( m.expandPrefix( ":z" ) );
		Set<Resource> loops = CycleFinder.findCycles( x );
		assertEquals( CollectionUtils.set(y, z), loops );
	}
	
	// this is the test case that was missing and allowed the cycle-finder
	// to miss items on a different path to the same cyclic node. Oops.
	@Test public void addsBothTraces() {
		Model m = ModelIOUtils.modelFromTurtle( ":x :P :y. :y :Q :z. :z :R :x. :x :S :a. :a :T :b. :b :U :x." );
		Resource x = m.createResource( m.expandPrefix( ":x" ) );
		Resource y = m.createResource( m.expandPrefix( ":y" ) );
		Resource z = m.createResource( m.expandPrefix( ":z" ) );
		Resource a = m.createResource( m.expandPrefix( ":a" ) );
		Resource b = m.createResource( m.expandPrefix( ":b" ) );		
		Set<Resource> loops = CycleFinder.findCycles( x );
		assertEquals( CollectionUtils.set(x, y, z, a, b), loops );
	}
	
	@Test public void testViscousCycles() {
		Model m = ModelIOUtils.modelFromTurtle( ":x :P :y. :x :P :w. :y :P :z. :w :P :z. :x :P :z. :z :P :x." );
		Resource x = m.createResource( m.expandPrefix( ":x" ) );
		Resource y = m.createResource( m.expandPrefix( ":y" ) );
		Resource w = m.createResource( m.expandPrefix( ":w" ) );
		Resource z = m.createResource( m.expandPrefix( ":z" ) );		
		Set<Resource> loops = CycleFinder.findCycles( x );
		assertEquals( CollectionUtils.set(x, y, w, z), loops );
	}

	@Test  public void testHorribleExampleTime() {
		StringBuilder sb = new StringBuilder();
		for (String line: exampleLines) sb.append( line ).append( '\n' );
		Model m = ModelIOUtils.modelFromTurtle( sb.toString() );
		long start = System.currentTimeMillis();
		CycleFinder.findCycles( m.createResource( "http://training.epimorphics.com/transport/london-underground/line/jubilee" ) );
		long timeTaken = System.currentTimeMillis() - start;
		if (timeTaken > 100) fail( "Took too long to do cycle detection." );
	} 
		
	String [] exampleLines = new String[]
		{
		"@prefix os:    <http://a9.com/-/spec/opensearch/1.1/> ."
		, "@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> ."
		, "@prefix geo:   <http://www.w3.org/2003/01/geo/wgs84_pos#> ."
		, "@prefix transport: <http://training.epimorphics.com/transport/def/metro/> ."
		, "@prefix dct:   <http://purl.org/dc/terms/> ."
		, "@prefix lu-line: <http://training.epimorphics.com/transport/london-underground/line/> ."
		, "@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> ."
		, "@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> ."
		, "@prefix api:   <http://purl.org/linked-data/api/vocab#> ."
		, "@prefix lu-station: <http://training.epimorphics.com/transport/london-underground/station/> ."
		, "@prefix xhv:   <http://www.w3.org/1999/xhtml/vocab#> ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/queensbury/kingsbury>"
		, "        transport:fromStop  lu-station:queensbury ;"
		, "        transport:toStop    lu-station:kingsbury ."
		, ""
		, "lu-station:swiss-cottage"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'Swiss Cottage' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/st-johns-wood/swiss-cottage> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/finchley-road/swiss-cottage> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/swiss-cottage/st-johns-wood> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/swiss-cottage/finchley-road> ;"
		, "        geo:lat                       51.5432 ;"
		, "        geo:long                      -0.1738 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/st-johns-wood/baker-street>"
		, "        transport:fromStop  lu-station:st-johns-wood ;"
		, "        transport:toStop    lu-station:baker-street ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/canary-wharf/north-greenwich>"
		, "        transport:fromStop  lu-station:canary-wharf ;"
		, "        transport:toStop    lu-station:north-greenwich ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/west-hampstead/finchley-road>"
		, "        transport:fromStop  lu-station:west-hampstead ;"
		, "        transport:toStop    lu-station:finchley-road ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/neasden/wembley-park>"
		, "        transport:fromStop  lu-station:neasden ;"
		, "        transport:toStop    lu-station:wembley-park ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/stanmore/canons-park>"
		, "        transport:fromStop  lu-station:stanmore ;"
		, "        transport:toStop    lu-station:canons-park ."
		, ""
		, "lu-station:north-greenwich"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'North Greenwich' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canning-town/north-greenwich> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canary-wharf/north-greenwich> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/north-greenwich/canning-town> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/north-greenwich/canary-wharf> ;"
		, "        geo:lat                       51.5005 ;"
		, "        geo:long                      0.0039 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/willesden-green/kilburn>"
		, "        transport:fromStop  lu-station:willesden-green ;"
		, "        transport:toStop    lu-station:kilburn ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/west-hampstead/kilburn>"
		, "        transport:fromStop  lu-station:west-hampstead ;"
		, "        transport:toStop    lu-station:kilburn ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/canary-wharf/canada-water>"
		, "        transport:fromStop  lu-station:canary-wharf ;"
		, "        transport:toStop    lu-station:canada-water ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/west-ham/canning-town>"
		, "        transport:fromStop  lu-station:west-ham ;"
		, "        transport:toStop    lu-station:canning-town ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/canada-water/bermondsey>"
		, "        transport:fromStop  lu-station:canada-water ;"
		, "        transport:toStop    lu-station:bermondsey ."
		, ""
		, "lu-station:wembley-park"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'Wembley Park' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/neasden/wembley-park> , <http://training.epimorphics.com/transport/london-underground/connection/metropolitan/preston-road/wembley-park> , <http://training.epimorphics.com/transport/london-underground/connection/metropolitan/finchley-road/wembley-park> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/kingsbury/wembley-park> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/wembley-park/kingsbury> , <http://training.epimorphics.com/transport/london-underground/connection/metropolitan/wembley-park/preston-road> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/wembley-park/neasden> , <http://training.epimorphics.com/transport/london-underground/connection/metropolitan/wembley-park/finchley-road> ;"
		, "        geo:lat                       51.5635 ;"
		, "        geo:long                      -0.2795 ."
		, ""
		, "lu-station:kilburn  a                 transport:UndergroundStation ;"
		, "        rdfs:label                    'Kilburn' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/willesden-green/kilburn> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/west-hampstead/kilburn> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/kilburn/willesden-green> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/kilburn/west-hampstead> ;"
		, "        geo:lat                       51.5471 ;"
		, "        geo:long                      -0.2047 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/waterloo/westminster>"
		, "        transport:fromStop  lu-station:waterloo ;"
		, "        transport:toStop    lu-station:westminster ."
		, ""
		, "lu-station:canary-wharf"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'Canary Wharf' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/docklands-light-railway/west-india-quay/canary-wharf> , <http://training.epimorphics.com/transport/london-underground/connection/docklands-light-railway/heron-quays/canary-wharf> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canada-water/canary-wharf> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/north-greenwich/canary-wharf> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canary-wharf/north-greenwich> , <http://training.epimorphics.com/transport/london-underground/connection/docklands-light-railway/canary-wharf/west-india-quay> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canary-wharf/canada-water> , <http://training.epimorphics.com/transport/london-underground/connection/docklands-light-railway/canary-wharf/heron-quays> ;"
		, "        geo:lat                       51.5051 ;"
		, "        geo:long                      -0.0209 ."
		, ""
		, "lu-station:waterloo  a                transport:UndergroundStation ;"
		, "        rdfs:label                    'Waterloo' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/waterloo-and-city/bank/waterloo> , <http://training.epimorphics.com/transport/london-underground/connection/bakerloo/lambeth-north/waterloo> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/westminster/waterloo> , <http://training.epimorphics.com/transport/london-underground/connection/northern/kennington/waterloo> , <http://training.epimorphics.com/transport/london-underground/connection/bakerloo/embankment/waterloo> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/southwark/waterloo> , <http://training.epimorphics.com/transport/london-underground/connection/northern/embankment/waterloo> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/waterloo/westminster> , <http://training.epimorphics.com/transport/london-underground/connection/bakerloo/waterloo/embankment> , <http://training.epimorphics.com/transport/london-underground/connection/northern/waterloo/embankment> , <http://training.epimorphics.com/transport/london-underground/connection/northern/waterloo/kennington> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/waterloo/southwark> , <http://training.epimorphics.com/transport/london-underground/connection/bakerloo/waterloo/lambeth-north> , <http://training.epimorphics.com/transport/london-underground/connection/waterloo-and-city/waterloo/bank> ;"
		, "        geo:lat                       51.5036 ;"
		, "        geo:long                      -0.1143 ."
		, ""
		, "lu-station:canning-town"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'Canning Town' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/docklands-light-railway/royal-victoria/canning-town> , <http://training.epimorphics.com/transport/london-underground/connection/docklands-light-railway/west-silvertown/canning-town> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/west-ham/canning-town> , <http://training.epimorphics.com/transport/london-underground/connection/docklands-light-railway/east-india/canning-town> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/north-greenwich/canning-town> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/docklands-light-railway/canning-town/royal-victoria> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canning-town/west-ham> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canning-town/north-greenwich> , <http://training.epimorphics.com/transport/london-underground/connection/docklands-light-railway/canning-town/east-india> , <http://training.epimorphics.com/transport/london-underground/connection/docklands-light-railway/canning-town/west-silvertown> ;"
		, "        geo:lat                       51.5147 ;"
		, "        geo:long                      0.0082 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/kingsbury/queensbury>"
		, "        transport:fromStop  lu-station:kingsbury ;"
		, "        transport:toStop    lu-station:queensbury ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/london-bridge/southwark>"
		, "        transport:fromStop  lu-station:london-bridge ;"
		, "        transport:toStop    lu-station:southwark ."
		, ""
		, "lu-station:west-ham  a                transport:UndergroundStation ;"
		, "        rdfs:label                    'West Ham' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/district/bromleybybow/west-ham> , <http://training.epimorphics.com/transport/london-underground/connection/district/plaistow/west-ham> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canning-town/west-ham> , <http://training.epimorphics.com/transport/london-underground/connection/hammersmith-and-city/plaistow/west-ham> , <http://training.epimorphics.com/transport/london-underground/connection/hammersmith-and-city/bromleybybow/west-ham> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/stratford/west-ham> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/hammersmith-and-city/west-ham/plaistow> , <http://training.epimorphics.com/transport/london-underground/connection/hammersmith-and-city/west-ham/bromleybybow> , <http://training.epimorphics.com/transport/london-underground/connection/district/west-ham/plaistow> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/west-ham/stratford> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/west-ham/canning-town> , <http://training.epimorphics.com/transport/london-underground/connection/district/west-ham/bromleybybow> ;"
		, "        geo:lat                       51.5287 ;"
		, "        geo:long                      0.0056 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/bermondsey/london-bridge>"
		, "        transport:fromStop  lu-station:bermondsey ;"
		, "        transport:toStop    lu-station:london-bridge ."
		, ""
		, "lu-station:bermondsey"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'Bermondsey' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/london-bridge/bermondsey> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canada-water/bermondsey> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/bermondsey/london-bridge> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/bermondsey/canada-water> ;"
		, "        geo:lat                       51.4979 ;"
		, "        geo:long                      -0.0637 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/swiss-cottage/finchley-road>"
		, "        transport:fromStop  lu-station:swiss-cottage ;"
		, "        transport:toStop    lu-station:finchley-road ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/waterloo/southwark>"
		, "        transport:fromStop  lu-station:waterloo ;"
		, "        transport:toStop    lu-station:southwark ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/westminster/waterloo>"
		, "        transport:fromStop  lu-station:westminster ;"
		, "        transport:toStop    lu-station:waterloo ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/dollis-hill/willesden-green>"
		, "        transport:fromStop  lu-station:dollis-hill ;"
		, "        transport:toStop    lu-station:willesden-green ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/kingsbury/wembley-park>"
		, "        transport:fromStop  lu-station:kingsbury ;"
		, "        transport:toStop    lu-station:wembley-park ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/southwark/waterloo>"
		, "        transport:fromStop  lu-station:southwark ;"
		, "        transport:toStop    lu-station:waterloo ."
		, ""
		, "lu-station:kingsbury  a               transport:UndergroundStation ;"
		, "        rdfs:label                    'Kingsbury' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/wembley-park/kingsbury> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/queensbury/kingsbury> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/kingsbury/wembley-park> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/kingsbury/queensbury> ;"
		, "        geo:lat                       51.5846 ;"
		, "        geo:long                      -0.2786 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/dollis-hill/neasden>"
		, "        transport:fromStop  lu-station:dollis-hill ;"
		, "        transport:toStop    lu-station:neasden ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/westminster/green-park>"
		, "        transport:fromStop  lu-station:westminster ;"
		, "        transport:toStop    lu-station:green-park ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/swiss-cottage/st-johns-wood>"
		, "        transport:fromStop  lu-station:swiss-cottage ;"
		, "        transport:toStop    lu-station:st-johns-wood ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/stratford/west-ham>"
		, "        transport:fromStop  lu-station:stratford ;"
		, "        transport:toStop    lu-station:west-ham ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/bond-street/green-park>"
		, "        transport:fromStop  lu-station:bond-street ;"
		, "        transport:toStop    lu-station:green-park ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/canning-town/west-ham>"
		, "        transport:fromStop  lu-station:canning-town ;"
		, "        transport:toStop    lu-station:west-ham ."
		, ""
		, "lu-station:willesden-green"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'Willesden Green' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/kilburn/willesden-green> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/dollis-hill/willesden-green> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/willesden-green/kilburn> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/willesden-green/dollis-hill> ;"
		, "        geo:lat                       51.5492 ;"
		, "        geo:long                      -0.2215 ."
		, ""
		, "lu-station:dollis-hill"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'Dollis Hill' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/willesden-green/dollis-hill> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/neasden/dollis-hill> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/dollis-hill/willesden-green> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/dollis-hill/neasden> ;"
		, "        geo:lat                       51.552 ;"
		, "        geo:long                      -0.2387 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/canning-town/north-greenwich>"
		, "        transport:fromStop  lu-station:canning-town ;"
		, "        transport:toStop    lu-station:north-greenwich ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/baker-street/bond-street>"
		, "        transport:fromStop  lu-station:baker-street ;"
		, "        transport:toStop    lu-station:bond-street ."
		, ""
		, "lu-station:queensbury"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'Queensbury' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/kingsbury/queensbury> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canons-park/queensbury> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/queensbury/kingsbury> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/queensbury/canons-park> ;"
		, "        geo:lat                       51.5942 ;"
		, "        geo:long                      -0.2861 ."
		, ""
		, "lu-station:green-park"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'Green Park' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/piccadilly/hyde-park-corner/green-park> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/bond-street/green-park> , <http://training.epimorphics.com/transport/london-underground/connection/victoria/victoria/green-park> , <http://training.epimorphics.com/transport/london-underground/connection/piccadilly/picadilly-circus/green-park> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/westminster/green-park> , <http://training.epimorphics.com/transport/london-underground/connection/victoria/oxford-circus/green-park> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/piccadilly/green-park/hyde-park-corner> , <http://training.epimorphics.com/transport/london-underground/connection/piccadilly/green-park/picadilly-circus> , <http://training.epimorphics.com/transport/london-underground/connection/victoria/green-park/oxford-circus> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/green-park/westminster> , <http://training.epimorphics.com/transport/london-underground/connection/victoria/green-park/victoria> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/green-park/bond-street> ;"
		, "        geo:lat                       51.5067 ;"
		, "        geo:long                      -0.1428 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/queensbury/canons-park>"
		, "        transport:fromStop  lu-station:queensbury ;"
		, "        transport:toStop    lu-station:canons-park ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/kilburn/west-hampstead>"
		, "        transport:fromStop  lu-station:kilburn ;"
		, "        transport:toStop    lu-station:west-hampstead ."
		, ""
		, "lu-station:stratford  a               transport:UndergroundStation ;"
		, "        rdfs:label                    'Stratford' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/central/leyton/stratford> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/west-ham/stratford> , <http://training.epimorphics.com/transport/london-underground/connection/docklands-light-railway/pudding-mill-lane/stratford> , <http://training.epimorphics.com/transport/london-underground/connection/central/mile-end/stratford> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/central/stratford/mile-end> , <http://training.epimorphics.com/transport/london-underground/connection/docklands-light-railway/stratford/pudding-mill-lane> , <http://training.epimorphics.com/transport/london-underground/connection/central/stratford/leyton> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/stratford/west-ham> ;"
		, "        geo:lat                       51.5416 ;"
		, "        geo:long                      -0.0042 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/canons-park/stanmore>"
		, "        transport:fromStop  lu-station:canons-park ;"
		, "        transport:toStop    lu-station:stanmore ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/st-johns-wood/swiss-cottage>"
		, "        transport:fromStop  lu-station:st-johns-wood ;"
		, "        transport:toStop    lu-station:swiss-cottage ."
		, ""
		, "lu-station:london-bridge"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'London Bridge' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/bermondsey/london-bridge> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/southwark/london-bridge> , <http://training.epimorphics.com/transport/london-underground/connection/northern/borough/london-bridge> , <http://training.epimorphics.com/transport/london-underground/connection/northern/bank/london-bridge> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/northern/london-bridge/borough> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/london-bridge/southwark> , <http://training.epimorphics.com/transport/london-underground/connection/northern/london-bridge/bank> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/london-bridge/bermondsey> ;"
		, "        geo:lat                       51.5052 ;"
		, "        geo:long                      -0.0864 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/canons-park/queensbury>"
		, "        transport:fromStop  lu-station:canons-park ;"
		, "        transport:toStop    lu-station:queensbury ."
		, ""
		, "lu-station:baker-street"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'Baker Street' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/bakerloo/regents-park/baker-street> , <http://training.epimorphics.com/transport/london-underground/connection/circle/edgware-road-c/baker-street> , <http://training.epimorphics.com/transport/london-underground/connection/hammersmith-and-city/great-portland-street/baker-street> , <http://training.epimorphics.com/transport/london-underground/connection/hammersmith-and-city/edgware-road-c/baker-street> , <http://training.epimorphics.com/transport/london-underground/connection/bakerloo/marylebone/baker-street> , <http://training.epimorphics.com/transport/london-underground/connection/metropolitan/great-portland-street/baker-street> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/bond-street/baker-street> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/st-johns-wood/baker-street> , <http://training.epimorphics.com/transport/london-underground/connection/metropolitan/finchley-road/baker-street> , <http://training.epimorphics.com/transport/london-underground/connection/circle/great-portland-street/baker-street> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/circle/baker-street/edgware-road-c> , <http://training.epimorphics.com/transport/london-underground/connection/bakerloo/baker-street/marylebone> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/baker-street/st-johns-wood> , <http://training.epimorphics.com/transport/london-underground/connection/metropolitan/baker-street/great-portland-street> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/baker-street/bond-street> , <http://training.epimorphics.com/transport/london-underground/connection/bakerloo/baker-street/regents-park> , <http://training.epimorphics.com/transport/london-underground/connection/hammersmith-and-city/baker-street/edgware-road-c> , <http://training.epimorphics.com/transport/london-underground/connection/hammersmith-and-city/baker-street/great-portland-street> , <http://training.epimorphics.com/transport/london-underground/connection/metropolitan/baker-street/finchley-road> , <http://training.epimorphics.com/transport/london-underground/connection/circle/baker-street/great-portland-street> ;"
		, "        geo:lat                       51.5226 ;"
		, "        geo:long                      -0.1571 ."
		, ""
		, "lu-station:southwark  a               transport:UndergroundStation ;"
		, "        rdfs:label                    'Southwark' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/waterloo/southwark> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/london-bridge/southwark> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/southwark/waterloo> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/southwark/london-bridge> ;"
		, "        geo:lat                       51.504 ;"
		, "        geo:long                      -0.1052 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/neasden/dollis-hill>"
		, "        transport:fromStop  lu-station:neasden ;"
		, "        transport:toStop    lu-station:dollis-hill ."
		, ""
		, "lu-station:stanmore  a                transport:UndergroundStation ;"
		, "        rdfs:label                    'Stanmore' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canons-park/stanmore> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/stanmore/canons-park> ;"
		, "        geo:lat                       51.6194 ;"
		, "        geo:long                      -0.3028 ."
		, ""
		, "lu-line:jubilee  a            transport:UndergroundLine ;"
		, "        rdfs:label            'Jubilee Line' ;"
		, "        transport:connection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/finchley-road/swiss-cottage> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/neasden/dollis-hill> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/queensbury/canons-park> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/willesden-green/dollis-hill> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/london-bridge/bermondsey> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/waterloo/southwark> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canning-town/north-greenwich> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/green-park/westminster> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/dollis-hill/willesden-green> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/westminster/green-park> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/dollis-hill/neasden> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/baker-street/bond-street> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/west-hampstead/kilburn> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/baker-street/st-johns-wood> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/st-johns-wood/baker-street> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/swiss-cottage/st-johns-wood> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/westminster/waterloo> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/southwark/waterloo> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/wembley-park/kingsbury> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/west-hampstead/finchley-road> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/stratford/west-ham> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/bond-street/baker-street> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/london-bridge/southwark> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/wembley-park/neasden> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/waterloo/westminster> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canada-water/bermondsey> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/kilburn/west-hampstead> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canons-park/queensbury> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/kilburn/willesden-green> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/bermondsey/canada-water> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/kingsbury/queensbury> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/southwark/london-bridge> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/west-ham/stratford> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/west-ham/canning-town> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/willesden-green/kilburn> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/st-johns-wood/swiss-cottage> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canary-wharf/north-greenwich> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/neasden/wembley-park> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/north-greenwich/canning-town> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canada-water/canary-wharf> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/north-greenwich/canary-wharf> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/bermondsey/london-bridge> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canning-town/west-ham> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/green-park/bond-street> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/kingsbury/wembley-park> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/finchley-road/west-hampstead> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/stanmore/canons-park> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canary-wharf/canada-water> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/queensbury/kingsbury> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/swiss-cottage/finchley-road> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canons-park/stanmore> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/bond-street/green-park> ;"
		, "        transport:terminal    lu-station:stratford , lu-station:stanmore ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/west-ham/stratford>"
		, "        transport:fromStop  lu-station:west-ham ;"
		, "        transport:toStop    lu-station:stratford ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/finchley-road/swiss-cottage>"
		, "        transport:fromStop  lu-station:finchley-road ;"
		, "        transport:toStop    lu-station:swiss-cottage ."
		, ""
		, "lu-station:west-hampstead"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'West Hampstead' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/kilburn/west-hampstead> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/finchley-road/west-hampstead> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/west-hampstead/kilburn> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/west-hampstead/finchley-road> ;"
		, "        geo:lat                       51.5469 ;"
		, "        geo:long                      -0.1906 ."
		, ""
		, "lu-station:finchley-road"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'Finchley Road' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/west-hampstead/finchley-road> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/swiss-cottage/finchley-road> , <http://training.epimorphics.com/transport/london-underground/connection/metropolitan/wembley-park/finchley-road> , <http://training.epimorphics.com/transport/london-underground/connection/metropolitan/baker-street/finchley-road> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/finchley-road/swiss-cottage> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/finchley-road/west-hampstead> , <http://training.epimorphics.com/transport/london-underground/connection/metropolitan/finchley-road/wembley-park> , <http://training.epimorphics.com/transport/london-underground/connection/metropolitan/finchley-road/baker-street> ;"
		, "        geo:lat                       51.5472 ;"
		, "        geo:long                      -0.1803 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/green-park/westminster>"
		, "        transport:fromStop  lu-station:green-park ;"
		, "        transport:toStop    lu-station:westminster ."
		, ""
		, "lu-station:canons-park"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'Canons Park' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/stanmore/canons-park> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/queensbury/canons-park> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canons-park/stanmore> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canons-park/queensbury> ;"
		, "        geo:lat                       51.6078 ;"
		, "        geo:long                      -0.2947 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/green-park/bond-street>"
		, "        transport:fromStop  lu-station:green-park ;"
		, "        transport:toStop    lu-station:bond-street ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/wembley-park/neasden>"
		, "        transport:fromStop  lu-station:wembley-park ;"
		, "        transport:toStop    lu-station:neasden ."
		, ""
		, "lu-station:canada-water"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'Canada Water' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/east-london/rotherhithe/canada-water> , <http://training.epimorphics.com/transport/london-underground/connection/east-london/surrey-quays/canada-water> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/bermondsey/canada-water> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canary-wharf/canada-water> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canada-water/bermondsey> , <http://training.epimorphics.com/transport/london-underground/connection/east-london/canada-water/surrey-quays> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/canada-water/canary-wharf> , <http://training.epimorphics.com/transport/london-underground/connection/east-london/canada-water/rotherhithe> ;"
		, "        geo:lat                       51.4982 ;"
		, "        geo:long                      -0.0502 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/kilburn/willesden-green>"
		, "        transport:fromStop  lu-station:kilburn ;"
		, "        transport:toStop    lu-station:willesden-green ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/london-bridge/bermondsey>"
		, "        transport:fromStop  lu-station:london-bridge ;"
		, "        transport:toStop    lu-station:bermondsey ."
		, ""
		, "lu-station:st-johns-wood"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'St. John\\\'s Wood' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/swiss-cottage/st-johns-wood> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/baker-street/st-johns-wood> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/st-johns-wood/swiss-cottage> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/st-johns-wood/baker-street> ;"
		, "        geo:lat                       51.5347 ;"
		, "        geo:long                      -0.174 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/bond-street/baker-street>"
		, "        transport:fromStop  lu-station:bond-street ;"
		, "        transport:toStop    lu-station:baker-street ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/canada-water/canary-wharf>"
		, "        transport:fromStop  lu-station:canada-water ;"
		, "        transport:toStop    lu-station:canary-wharf ."
		, ""
		, "lu-station:westminster"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'Westminster' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/district/embankment/westminster> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/waterloo/westminster> , <http://training.epimorphics.com/transport/london-underground/connection/circle/embankment/westminster> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/green-park/westminster> , <http://training.epimorphics.com/transport/london-underground/connection/circle/st-jamess-park/westminster> , <http://training.epimorphics.com/transport/london-underground/connection/district/st-jamess-park/westminster> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/westminster/waterloo> , <http://training.epimorphics.com/transport/london-underground/connection/circle/westminster/embankment> , <http://training.epimorphics.com/transport/london-underground/connection/district/westminster/st-jamess-park> , <http://training.epimorphics.com/transport/london-underground/connection/circle/westminster/st-jamess-park> , <http://training.epimorphics.com/transport/london-underground/connection/district/westminster/embankment> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/westminster/green-park> ;"
		, "        geo:lat                       51.501 ;"
		, "        geo:long                      -0.1254 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/bermondsey/canada-water>"
		, "        transport:fromStop  lu-station:bermondsey ;"
		, "        transport:toStop    lu-station:canada-water ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/wembley-park/kingsbury>"
		, "        transport:fromStop  lu-station:wembley-park ;"
		, "        transport:toStop    lu-station:kingsbury ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/southwark/london-bridge>"
		, "        transport:fromStop  lu-station:southwark ;"
		, "        transport:toStop    lu-station:london-bridge ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/finchley-road/west-hampstead>"
		, "        transport:fromStop  lu-station:finchley-road ;"
		, "        transport:toStop    lu-station:west-hampstead ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/willesden-green/dollis-hill>"
		, "        transport:fromStop  lu-station:willesden-green ;"
		, "        transport:toStop    lu-station:dollis-hill ."
		, ""
		, "lu-station:bond-street"
		, "        a                             transport:UndergroundStation ;"
		, "        rdfs:label                    'Bond Street' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/central/marble-arch/bond-street> , <http://training.epimorphics.com/transport/london-underground/connection/central/oxford-circus/bond-street> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/green-park/bond-street> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/baker-street/bond-street> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/central/bond-street/marble-arch> , <http://training.epimorphics.com/transport/london-underground/connection/central/bond-street/oxford-circus> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/bond-street/green-park> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/bond-street/baker-street> ;"
		, "        geo:lat                       51.5142 ;"
		, "        geo:long                      -0.1494 ."
		, ""
		, "lu-station:neasden  a                 transport:UndergroundStation ;"
		, "        rdfs:label                    'Neasden' ;"
		, "        transport:incomingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/wembley-park/neasden> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/dollis-hill/neasden> ;"
		, "        transport:outgoingConnection  <http://training.epimorphics.com/transport/london-underground/connection/jubilee/neasden/wembley-park> , <http://training.epimorphics.com/transport/london-underground/connection/jubilee/neasden/dollis-hill> ;"
		, "        geo:lat                       51.5542 ;"
		, "        geo:long                      -0.2503 ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/baker-street/st-johns-wood>"
		, "        transport:fromStop  lu-station:baker-street ;"
		, "        transport:toStop    lu-station:st-johns-wood ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/north-greenwich/canary-wharf>"
		, "        transport:fromStop  lu-station:north-greenwich ;"
		, "        transport:toStop    lu-station:canary-wharf ."
		, ""
		, "<http://training.epimorphics.com/transport/london-underground/connection/jubilee/north-greenwich/canning-town>"
		, "        transport:fromStop  lu-station:north-greenwich ;"
		, "        transport:toStop    lu-station:canning-town ."
		, ""
		, "<http://localhost:8080/anything.ttl?_properties=connection.fromStop.*,connection.toStop.*&type=UndergroundLine>"
		, "        a               api:ListEndpoint ;"
		, "        dct:hasPart     <http://localhost:8080/anything.ttl?type=UndergroundLine&_properties=connection.fromStop.*,connection.toStop.*&_pageSize=1> ;"
		, "        api:definition  <http://localhost:8080/meta/anything.ttl?_properties=connection.fromStop.*,connection.toStop.*&type=UndergroundLine> ."
		, ""
		, "<http://localhost:8080/anything.ttl?type=UndergroundLine&_properties=connection.fromStop.*,connection.toStop.*&_pageSize=1>"
		, "        a                            api:Page ;"
		, "        os:itemsPerPage              '1'^^xsd:long ;"
		, "        os:startIndex                '1'^^xsd:long ;"
		, "        dct:isPartOf                 <http://localhost:8080/anything.ttl?_properties=connection.fromStop.*,connection.toStop.*&type=UndergroundLine> ;"
		, "        api:definition               <http://localhost:8080/meta/anything.ttl?_properties=connection.fromStop.*,connection.toStop.*&type=UndergroundLine> ;"
		, "        api:extendedMetadataVersion  <http://localhost:8080/anything.ttl?_properties=connection.fromStop.*,connection.toStop.*&_metadata=all&_pageSize=1&type=UndergroundLine> ;"
		, "        api:items                    ( lu-line:jubilee ) ;"
		, "        api:page                     '0'^^xsd:long ;"
		, "        xhv:first                    <http://localhost:8080/anything.ttl?_properties=connection.fromStop.*,connection.toStop.*&_pageSize=1&type=UndergroundLine&_page=0> ;"
		, "        xhv:next                     <http://localhost:8080/anything.ttl?_properties=connection.fromStop.*,connection.toStop.*&_pageSize=1&type=UndergroundLine&_page=1> ."
		};
}
