/* CVS $Id: $ */
package com.epimorphics.lda.vocabularies; 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /home/der/projects/java-workspace/elda/elda-lda/../vocabs/elda_api.ttl 
 * @author Auto-generated by schemagen on 05 Feb 2026 18:29 
 */
@SuppressWarnings({"removal", "deprecated"})
public class ELDA_API  extends API {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.epimorphics.com/vocabularies/lda#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>class of SPARQL maps</p> */
    public static final Property SPARQLMap = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#SPARQLMap" );
    
    /** <p>Property of JSON-LD formatter that determines if all literals are rendered 
     *  with their types.</p>
     */
    public static final Property allLiteralsStructured = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#allLiteralsStructured" );
    
    /** <p>:</p> */
    public static final Property allowReserved = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#allowReserved" );
    
    /** <p></p> */
    public static final Property allowSyntaxProperties = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#allowSyntaxProperties" );
    
    /** <p>if present and true, allows a basic-auth SPARQL endpoint to connect without 
     *  using https. This should only be used if the connection to the endpoint is 
     *  already secure.</p>
     */
    public static final Property authAllowInsecure = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#authAllowInsecure" );
    
    /** <p>comma-separated list of file wildcarded paths for authentication files.</p> */
    public static final Property authFile = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#authFile" );
    
    /** <p>key identifying which authentication item to use.</p> */
    public static final Property authKey = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#authKey" );
    
    /** <p>If given a value, that is the cache expiry time in seconds for an endpoint 
     *  or family of endpoints.</p>
     */
    public static final Property cacheExpiryTime = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#cacheExpiryTime" );
    
    /** <p>name of one of Elda's cache policies.</p> */
    public static final Property cachePolicyName = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#cachePolicyName" );
    
    /** <p>If a JSON LD renderer has this property, its value determines whether the 
     *  renderer checks that the model has round-tripped through the generated JSON 
     *  LD.</p>
     */
    public static final Property checkJSONLDRoundTrip = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#checkJSONLDRoundTrip" );
    
    /** <p>full Java class name of an Elda formatter plugin.</p> */
    public static final Property className = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#className" );
    
    /** <p></p> */
    public static final Property construct = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#construct" );
    
    /** <p></p> */
    public static final Property describeAllLabel = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#describeAllLabel" );
    
    /** <p></p> */
    public static final Property describeThreshold = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#describeThreshold" );
    
    /** <p>Controls whether hardwired metadata is suppressed when rendering a result.</p> */
    public static final Property disable_default_metadata = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#disable-default-metadata" );
    
    /** <p></p> */
    public static final Property element = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#element" );
    
    /** <p>Controls whether hardwired metadata is suppressed when rendering a result.</p> */
    public static final Property enable_default_metadata = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#enable-default-metadata" );
    
    /** <p>If true, "true", or "yes", Elda will generate a total item count for any list-endpoint 
     *  query. If false, "false", or "no", it will not. Otherwise counting is enabled 
     *  using the _count query parameter.</p>
     */
    public static final Property enableCounting = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#enableCounting" );
    
    /** <p>If given the value true, then Elda generates an ETag for its results.</p> */
    public static final Property enableETags = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#enableETags" );
    
    /** <p></p> */
    public static final Property enableForwardHeaders = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#enableForwardHeaders" );
    
    /** <p>Determine whether to apply a forward closure to describe query results.</p> */
    public static final Property encloseDescribe = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#encloseDescribe" );
    
    /** <p></p> */
    public static final Property enhanceViewWith = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#enhanceViewWith" );
    
    /** <p></p> */
    public static final Property feedAuthorProperties = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#feedAuthorProperties" );
    
    /** <p></p> */
    public static final Property feedAuthors = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#feedAuthors" );
    
    /** <p></p> */
    public static final Property feedDateProperties = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#feedDateProperties" );
    
    /** <p></p> */
    public static final Property feedLabelProperties = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#feedLabelProperties" );
    
    /** <p></p> */
    public static final Property feedNamespace = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#feedNamespace" );
    
    /** <p></p> */
    public static final Property feedRights = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#feedRights" );
    
    /** <p></p> */
    public static final Property feedRightsProperties = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#feedRightsProperties" );
    
    /** <p></p> */
    public static final Property feedTitle = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#feedTitle" );
    
    /** <p>Configuration property to set the name of the queried graph from an endpoint-specific 
     *  template.</p>
     */
    public static final Property graphTemplate = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#graphTemplate" );
    
    /** <p></p> */
    public static final Property ifStarts = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#ifStarts" );
    
    /** <p>Configs can include sub-config fragments.</p> */
    public static final Property includesFragment = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#includesFragment" );
    
    /** <p>Property of a JSONFormatter that says if xsd:date and xsd:dateTime values 
     *  should be encoded based on ISO 8601. Default value is false.</p>
     */
    public static final Property jsonUsesISOdate = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#jsonUsesISOdate" );
    
    /** <p>Configuration property to set a URL for a licence for the response page or 
     *  a way of extracting licence URLs from the SPARQL endpoint. There can be many 
     *  such licences.</p>
     */
    public static final Property license = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#license" );
    
    /** <p></p> */
    public static final Property listURL = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#listURL" );
    
    /** <p></p> */
    public static final Property loadedFrom = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#loadedFrom" );
    
    /** <p>value to use as the argument to the map lookup.</p> */
    public static final Property mapFrom = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#mapFrom" );
    
    /** <p>name of argument variable in map.</p> */
    public static final Property mapIn = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#mapIn" );
    
    /** <p>specifies map name for lookup</p> */
    public static final Property mapName = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#mapName" );
    
    /** <p>name of result variable in map.</p> */
    public static final Property mapOut = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#mapOut" );
    
    public static final Property mapQuery = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#mapQuery" );
    
    /** <p>object is reference to Elda SPARQL map resource.</p> */
    public static final Property mapWith = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#mapWith" );
    
    /** <p></p> */
    public static final Property match = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#match" );
    
    /** <p>Property mapping from page to metadata for JSON-LD rendering.</p> */
    public static final Property meta = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#meta" );
    
    /** <p></p> */
    public static final Property metaURL = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#metaURL" );
    
    /** <p>Property used in Elda metadata block declarations.</p> */
    public static final Property metadata = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#metadata" );
    
    /** <p></p> */
    public static final Property metadataOptions = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#metadataOptions" );
    
    /** <p>Attatches a notice (eg deprecation) to a generated page.</p> */
    public static final Property notice = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#notice" );
    
    /** <p>Property of an API spec or endpoint that says whether suspicious characters 
     *  should be dropped from a query parameter filter value.</p>
     */
    public static final Property purgeFilterValues = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#purgeFilterValues" );
    
    /** <p></p> */
    public static final Property replaceStartBy = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#replaceStartBy" );
    
    /** <p></p> */
    public static final Property rewriteResultURIs = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#rewriteResultURIs" );
    
    /** <p></p> */
    public static final Property shortnameMode = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#shortnameMode" );
    
    /** <p>property connecting API spec to its SPARQL query map.</p> */
    public static final Property sparqlMap = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#sparqlMap" );
    
    /** <p></p> */
    public static final Property sparqlQuery = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#sparqlQuery" );
    
    /** <p></p> */
    public static final Property supportsNestedSelect = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#supportsNestedSelect" );
    
    /** <p>Property from page to term bindings</p> */
    public static final Property termBinding = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#termBinding" );
    
    /** <p></p> */
    public static final Property textContentProperty = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#textContentProperty" );
    
    public static final Property textPlaceEarly = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#textPlaceEarly" );
    
    /** <p></p> */
    public static final Property textQueryProperty = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#textQueryProperty" );
    
    /** <p></p> */
    public static final Property textSearchOperand = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#textSearchOperand" );
    
    /** <p></p> */
    public static final Property uriTemplatePrefix = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#uriTemplatePrefix" );
    
    /** <p></p> */
    public static final Property velocityTemplate = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#velocityTemplate" );
    
    /** <p></p> */
    public static final Property viewName = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#viewName" );
    
    public static final Property vocabFallback = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#vocabFallback" );
    
    /** <p></p> */
    public static final Property wantsContext = M_MODEL.createProperty( "http://www.epimorphics.com/vocabularies/lda#wantsContext" );
    
    /** <p></p> */
    public static final Resource Combiner = M_MODEL.createResource( "http://www.epimorphics.com/vocabularies/lda#Combiner" );
    
    /** <p></p> */
    public static final Resource FeedFormatter = M_MODEL.createResource( "http://www.epimorphics.com/vocabularies/lda#FeedFormatter" );
    
    /** <p></p> */
    public static final Resource VelocityFormatter = M_MODEL.createResource( "http://www.epimorphics.com/vocabularies/lda#VelocityFormatter" );
    
    /** <p></p> */
    public static final Resource preferLocalnames = M_MODEL.createResource( "http://www.epimorphics.com/vocabularies/lda#preferLocalnames" );
    
    /** <p></p> */
    public static final Resource preferPrefixes = M_MODEL.createResource( "http://www.epimorphics.com/vocabularies/lda#preferPrefixes" );
    
    /** <p></p> */
    public static final Resource roundTrip = M_MODEL.createResource( "http://www.epimorphics.com/vocabularies/lda#roundTrip" );
    
}
