package temp;

import java.io.ByteArrayInputStream;
import java.io.UnsupportedEncodingException;

import org.junit.Ignore;
import org.junit.Test;

import com.github.jsonldjava.jena.JenaJSONLD;
import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;

public class TestJsonLdLibrary {
	
	static { JenaJSONLD.init(); }
	
	@Test @Ignore public void testReadsJSON_LD() throws UnsupportedEncodingException {
					
		
		Model reconstituted = ModelFactory.createDefaultModel();
		
		String source = response;
		
		reconstituted.read(new ByteArrayInputStream(source.getBytes("UTF-8")), "", "JSON-LD");
		System.err.println(">> reconstituted "+ reconstituted.size() + " triples.");
		reconstituted.write(System.err, "TURTLE");
		System.err.println(">> done.");
	}	
	
	static final String example =
		joinup
			( "\"@context\": {\"name\": \"eh:/bandersnatch/name\", \"born\": \"eh:/bandersnatch/born\"}"
			, "\"@id\": \"http://dbpedia.org/resource/John_Lennon\""
			, "\"name\": \"John Lennon\""
			, "\"born\": \"1940-10-09\""
			, "\"spouse\": \"http://dbpedia.org/resource/Cynthia_Lennon\""		
			);
	
	static final String response = joinup2(
    "	{",
    "",
    "	    \"@context\": ",
    "",
    "	{",
    "",
    "	    \"isPartOf\": \"http://purl.org/dc/terms/isPartOf\",",
    "	    \"rest\": \"http://www.w3.org/1999/02/22-rdf-syntax-ns#rest\",",
    "		\"results\": \"eh:/results\",",
    "	    \"playTimeMinutes\": ",
    "",
    "	{",
    "",
    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/playTimeMinutes\",",
    "	    \"@type\": \"http://www.w3.org/2001/XMLSchema#integer\"",
    "",
    "	},",
    "	\"publicationYear\": ",
    "	{",
    "",
    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/pubYear\",",
    "	    \"@type\": \"http://www.w3.org/2001/XMLSchema#integer\"",
    "",
    "	},",
//    "	\"next\": \"http://www.w3.org/1999/xhtml/vocab#next\",",
//    "	\"definition\": \"http://purl.org/linked-data/api/vocab#definition\",",
//    "	\"BoardGame\": \"http://epimorphics.com/public/vocabulary/games/BoardGame\",",
//    "	\"first\": \"http://www.w3.org/1999/02/22-rdf-syntax-ns#first\",",
//    "	\"seeAlso\": \"http://www.w3.org/2000/01/rdf-schema#seeAlso\",",
//    "	\"type\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://www.w3.org/1999/02/22-rdf-syntax-ns#type\",",
//    "	    \"@type\": \"http://www.w3.org/2000/01/rdf-schema#Class\"",
//    "",
//    "	},",
//    "	\"publishedBy\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/published-by\",",
//    "	    \"@type\": \"http://www.w3.org/2000/01/rdf-schema#Class\"",
//    "",
//    "	},",
//    "	\"extendedMetadataVersion\": \"http://purl.org/linked-data/api/vocab#extendedMetadataVersion\",",
//    "	\"players\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/players\",",
//    "	    \"@type\": \"http://www.w3.org/2001/XMLSchema#int\"",
//    "",
//    "	},",
//    "	\"designedBy\": ",
//    "",
//    "	    {",
//    "	        \"@id\": \"http://epimorphics.com/public/vocabulary/games/designed-by\",",
//    "	        \"@type\": \"http://www.w3.org/2000/01/rdf-schema#Class\"",
//    "	    },",
//    "	    \"sameAs\": \"http://www.w3.org/2002/07/owl#sameAs\",",
//    "	    \"page\": \"http://purl.org/linked-data/api/vocab#page\",",
//    "	    \"items\": \"http://purl.org/linked-data/api/vocab#items\",",
//    "	    \"startIndex\": \"http://a9.com/-/spec/opensearch/1.1/startIndex\",",
//    "	    \"itemsPerPage\": \"http://a9.com/-/spec/opensearch/1.1/itemsPerPage\",",
//    "	    \"hasPart\": \"http://purl.org/dc/terms/hasPart\",",
    "	    \"label\": \"http://www.w3.org/2000/01/rdf-schema#label\"",
    "",
    "	},",
//    "	\"format\": \"linked-data-api\",",
//    "	\"version\": \"0.2A\",",
    "	\"meta\": ",
    "	{",
    "",
    "	    \"@id\": \"http://localhost:8080/standalone/again/games.json-ld\",",
//    "	    \"startIndex\": ​1,",
    "	    \"type\": ",
    "",
    "	[",
    "",
    "	{",
    "",
    "	    \"@id\": \"http://purl.org/linked-data/api/vocab#Page\"",
    "",
    "	},",
    "",
    "	    {",
    "	        \"@id\": \"http://purl.org/linked-data/api/vocab#ListEndpoint\"",
    "	    }",
    "",
    "	],",
    "	\"isPartOf\": ",
    "	{",
    "",
    "	    \"@id\": \"http://localhost:8080/standalone/again/games.json-ld\"",
    "",
    "	}",
//    "	\"definition\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://localhost:8080/standalone/again/meta/games.json-ld\"",
//    "",
//    "	},",
//    "	\"hasPart\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://localhost:8080/standalone/again/games.json-ld\"",
//    "",
//    "	},",
//    "	\"page\": ​0,",
//    "	\"extendedMetadataVersion\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://localhost:8080/standalone/again/games.json-ld?_metadata=all\"",
//    "",
//    "	},",
//    "	\"itemsPerPage\": ​10,",
//    "	\"next\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://localhost:8080/standalone/again/games.json-ld?_page=1\"",
//    "",
//    "	},",
//    "	\"first\": ",
//    "",
//    "	    {",
//    "	        \"@id\": \"http://localhost:8080/standalone/again/games.json-ld?_page=0\"",
//    "	    }",
    "",
    "	},",
    "	\"results\": ",
    "	[",
//    "",
    "	{",
    "",
    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/BriefHistoryOfTheWorld\",",
    "       \"publicationYear\": 2009,",
    "	    \"designedBy\": ",
    "",
    "	{",
    "",
    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/ragnar-brothers\"",
    "",
    "	},",
    "	\"type\": ",
    "	[",
    "",
    "	    {",
    "	        \"@id\": \"http://epimorphics.com/public/vocabulary/games/BoardGame\"",
    "	    }",
    "",
    "	],",
    "	\"players\": ",
    "	[",
    "",
    "      6,",
    "      5,",
    "      4,",
    "      3,6,5,4,3",
    "",
    "	],",
    "	\"sameAs\": ",
    "	{",
    "",
    "	    \"@id\": \"http://www.ragnarbrothers.co.uk/html/brief_history_of_the_world1.html\"",
    "",
    "	},",
    "	\"label\": ",
    "",
    "	    [",
    "	        \"A Brief History of the World\"",
    "	    ]",
    "",
    "	}",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/a-few-acres-of-snow\",",
//    "	    \"publicationYear\": ​2011,",
//    "	    \"designedBy\": ",
//    "",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/martin-wallace\"",
//    "",
//    "	},",
//    "	\"type\": ",
//    "	[",
//    "",
//    "	    {",
//    "	        \"@id\": \"http://epimorphics.com/public/vocabulary/games/BoardGame\"",
//    "	    }",
//    "",
//    "	],",
//    "	\"players\": ​2,",
//    "	\"sameAs\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://www.treefroggames.com/a-few-acres-of-snow-2\"",
//    "",
//    "	},",
//    "	\"label\": ",
//    "",
//    "	    [",
//    "	        \"A Few Acres of Snow\"",
//    "	    ],",
//    "	    \"playTimeMinutes\": ​60",
//    "",
//    "	},",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/age-of-industry\",",
//    "	    \"publicationYear\": ​2010,",
//    "	    \"designedBy\": ",
//    "",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/martin-wallace\"",
//    "",
//    "	},",
//    "	\"type\": ",
//    "	[",
//    "",
//    "	    {",
//    "	        \"@id\": \"http://epimorphics.com/public/vocabulary/games/BoardGame\"",
//    "	    }",
//    "",
//    "	],",
//    "	\"players\": ",
//    "	[",
//    "",
//    "	    ​5,",
//    "	    ​4,",
//    "	    ​3,",
//    "	    ​2",
//    "",
//    "	],",
//    "	\"sameAs\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://www.treefroggames.com/age-of-industry\"",
//    "",
//    "	},",
//    "	\"label\": ",
//    "",
//    "	    [",
//    "	        \"Age of Industry\"",
//    "	    ]",
//    "",
//    "	},",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/age-of-steam\",",
//    "	    \"publicationYear\": ​2002,",
//    "	    \"designedBy\": ",
//    "",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/martin-wallace\"",
//    "",
//    "	},",
//    "	\"type\": ",
//    "	[",
//    "",
//    "	    {",
//    "	        \"@id\": \"http://epimorphics.com/public/vocabulary/games/BoardGame\"",
//    "	    }",
//    "",
//    "	],",
//    "	\"players\": ",
//    "	[",
//    "",
//    "	    ​6,",
//    "	    ​5,",
//    "	    ​4,",
//    "	    ​3",
//    "",
//    "	],",
//    "	\"sameAs\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://www.treefroggames.com/age-of-steam\"",
//    "",
//    "	},",
//    "	\"label\": ",
//    "",
//    "	    [",
//    "	        \"Age of Steam\"",
//    "	    ]",
//    "",
//    "	},",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/canal-mania\",",
//    "	    \"publicationYear\": ​2006,",
//    "	    \"designedBy\": ",
//    "",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/ragnar-brothers\"",
//    "",
//    "	},",
//    "	\"type\": ",
//    "	[",
//    "",
//    "	    {",
//    "	        \"@id\": \"http://epimorphics.com/public/vocabulary/games/BoardGame\"",
//    "	    }",
//    "",
//    "	],",
//    "	\"players\": ",
//    "	[",
//    "",
//    "	    ​5,",
//    "	    ​4,",
//    "	    ​3,",
//    "	    ​2",
//    "",
//    "	],",
//    "	\"sameAs\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://www.ragnarbrothers.co.uk/html/canal_mania.html\"",
//    "",
//    "	},",
//    "	\"label\": ",
//    "",
//    "	    [",
//    "	        \"Canal Mania\"",
//    "	    ]",
//    "",
//    "	},",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/el-grande\",",
//    "	    \"designedBy\": ",
//    "",
//    "	[",
//    "",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/richard-ulrich\",",
//    "	    \"label\": ",
//    "",
//    "	    [",
//    "	        \"Richard Ulrich\"",
//    "	    ]",
//    "",
//    "	},",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/Wolfgang_Kramer\",",
//    "	    \"label\": ",
//    "",
//    "	        [",
//    "	            \"Wolfgang Kramer\"",
//    "	        ]",
//    "	    }",
//    "",
//    "	],",
//    "	\"publicationYear\": ​1995,",
//    "	\"type\": ",
//    "	[",
//    "",
//    "	    {",
//    "	        \"@id\": \"http://epimorphics.com/public/vocabulary/games/BoardGame\"",
//    "	    }",
//    "",
//    "	],",
//    "	\"players\": ",
//    "	[",
//    "",
//    "	    ​3,",
//    "	    ​5,",
//    "	    ​4,",
//    "	    ​2",
//    "",
//    "	],",
//    "	\"sameAs\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://www.hans-im-glueck.de/el-grande\"",
//    "",
//    "	},",
//    "	\"label\": ",
//    "",
//    "	    [",
//    "	        \"El Grande\"",
//    "	    ]",
//    "",
//    "	},",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/glen-more\",",
//    "	    \"designedBy\": ",
//    "",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/matthias-cramer\"",
//    "",
//    "	},",
//    "	\"publicationYear\": ​2010,",
//    "	\"type\": ",
//    "	[",
//    "",
//    "	    {",
//    "	        \"@id\": \"http://epimorphics.com/public/vocabulary/games/BoardGame\"",
//    "	    }",
//    "",
//    "	],",
//    "	\"players\": ",
//    "	[",
//    "",
//    "	    ​2,",
//    "	    ​5,",
//    "	    ​4,",
//    "	    ​3",
//    "",
//    "	],",
//    "	\"sameAs\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://www.aleaspiele.de/Pages/C6/\"",
//    "",
//    "	},",
//    "	\"label\": ",
//    "	[",
//    "",
//    "	    \"Glen More\"",
//    "",
//    "	],",
//    "	\"playTimeMinutes\": ​60,",
//    "	\"publishedBy\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/Alea\",",
//    "	    \"label\": ",
//    "",
//    "	        [",
//    "	            \"Alea\"",
//    "	        ]",
//    "	    }",
//    "",
//    "	},",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/KingdomBuilder\",",
//    "	    \"seeAlso\": ",
//    "",
//    "	{",
//    "",
//    "	    \"@id\": \"http://boardgamegeek.com/boardgame/107529/kingdom-builder\"",
//    "",
//    "	},",
//    "	\"publicationYear\": ​2011,",
//    "	\"designedBy\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/donald-x-vaccarino\",",
//    "	    \"label\": ",
//    "",
//    "	    [",
//    "	        \"Donald X. Vaccarino\"",
//    "	    ]",
//    "",
//    "	},",
//    "	\"type\": ",
//    "	[",
//    "",
//    "	    {",
//    "	        \"@id\": \"http://epimorphics.com/public/vocabulary/games/BoardGame\"",
//    "	    }",
//    "",
//    "	],",
//    "	\"players\": ",
//    "	[",
//    "",
//    "	    ​4,",
//    "	    ​3,",
//    "	    ​2",
//    "",
//    "	],",
//    "	\"sameAs\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://queen-games.de/games.aspx?ProductId=45\"",
//    "",
//    "	},",
//    "	\"label\": ",
//    "",
//    "	    [",
//    "	        \"Kingdom Builder\"",
//    "	    ]",
//    "",
//    "	},",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/lancaster\",",
//    "	    \"designedBy\": ",
//    "",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/matthias-cramer\"",
//    "",
//    "	},",
//    "	\"publicationYear\": ​2011,",
//    "	\"type\": ",
//    "	[",
//    "",
//    "	    {",
//    "	        \"@id\": \"http://epimorphics.com/public/vocabulary/games/BoardGame\"",
//    "	    }",
//    "",
//    "	],",
//    "	\"players\": ",
//    "	[",
//    "",
//    "	    ​5,",
//    "	    ​2,",
//    "	    ​3,",
//    "	    ​4",
//    "",
//    "	],",
//    "	\"sameAs\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://boardgamegeek.com/boardgame/96913/lancaster\"",
//    "",
//    "	},",
//    "	\"label\": ",
//    "	[",
//    "",
//    "	    \"Lancaster\"",
//    "",
//    "	],",
//    "	\"playTimeMinutes\": ​60,",
//    "	\"publishedBy\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/queen-games\",",
//    "	    \"label\": ",
//    "",
//    "	        [",
//    "	            \"Queen Games\"",
//    "	        ]",
//    "	    }",
//    "",
//    "	},",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/last-train-to-wensleydale\",",
//    "	    \"publicationYear\": ​2009,",
//    "	    \"designedBy\": ",
//    "",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/martin-wallace\"",
//    "",
//    "	},",
//    "	\"type\": ",
//    "	[",
//    "",
//    "	    {",
//    "	        \"@id\": \"http://epimorphics.com/public/vocabulary/games/BoardGame\"",
//    "	    }",
//    "",
//    "	],",
//    "	\"players\": ",
//    "	[",
//    "",
//    "	    ​4,",
//    "	    ​3",
//    "",
//    "	],",
//    "	\"sameAs\": ",
//    "	{",
//    "",
//    "	    \"@id\": \"http://www.treefroggames.com/last-train-to-wensleydale\"",
//    "",
//    "	},",
//    "	\"label\": ",
//    "",
//    "	        [",
//    "	            \"Last Train to Wensleydale\"",
//    "	        ],",
//    "	        \"playTimeMinutes\": ​120",
//    "	    }",
//    "",
//    "	],",
//    "	\"others\": ",
//    "	[",
//    "",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/BoardGame\",",
//    "	    \"label\": ",
//    "",
//    "	    [",
//    "	        \"Board Game\"",
//    "	    ]",
//    "",
//    "	},",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/ragnar-brothers\",",
//    "	    \"label\": ",
//    "",
//    "	    [",
//    "	        \"Ragnar Brothers\"",
//    "	    ]",
//    "",
//    "	},",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/martin-wallace\",",
//    "	    \"label\": ",
//    "",
//    "	    [",
//    "	        \"Martin Wallace\"",
//    "	    ]",
//    "",
//    "	},",
//    "	{",
//    "",
//    "	    \"@id\": \"http://epimorphics.com/public/vocabulary/games/matthias-cramer\",",
//    "	    \"label\": ",
//    "",
//    "	            [",
//    "	                \"Matthias Cramer\"",
//    "	            ]",
//    "	        }",
    "	    ]",
    "",
    "	}"
	);
	
	static String joinup(String ...elements ) {
		StringBuilder sb = new StringBuilder();
		sb.append("{\n");
		String comma = ",";
		for (String x: elements) {
			sb.append(x).append(comma).append("\n");
		}
		sb.append("\"hack\": \"for parsing\"}\n");
		return sb.toString();
	}	
	
	static String joinup2(String ...elements ) {
		int line = 0;
		StringBuilder sb = new StringBuilder();
		for (String x: elements) {
			line += 1;
//			System.err.println("| " + line + ": " + x);
			sb.append(x).append("\n");
		}
		return sb.toString();
}

}
